"use server";
import { revalidatePath } from "next/cache";
import { laySessionHienHanh } from "@/lib/auth/session";
import { taoSupabaseServiceRole } from "@/lib/supabase/server";
import { kiemTraMaTran,type OMaTran } from "@/lib/rules/ma-tran-de-thi";
export type CauHoiPreview={id:string;phan:"I"|"II"|"III";chuyenDeId:string;mucDoId:string;nhomId:string|null;noiDung:string;chiTiet:{thuTu:number;noiDung:string}[]};
async function ctx(){const u=await laySessionHienHanh();if(!u||u.vai_tro!=="GiaoVien")throw new Error("Không có quyền");const s=taoSupabaseServiceRole();const {data:m}=await s.from("mon").select("*").eq("to_truong_tai_khoan_id",u.sub).maybeSingle();if(!m)throw new Error("Không phải Tổ trưởng");return {u,s,m};}
export async function kiemTraSucChua(maTran:OMaTran[]){
 try{const {s,m}=await ctx();const {data}=await s.from("cau_hoi").select("cau_hoi_id,phan,muc_do_id,nhom_id,bai_hoc!inner(chuyen_de!inner(chuyen_de_id,mon_id))").eq("bai_hoc.chuyen_de.mon_id",m.mon_id).eq("trang_thai_duyet","DaDuyet").eq("trang_thai_su_dung","ChuaDung").eq("trang_thai_hoat_dong","DangHoatDong");
 const map=new Map<string,Set<string>>();for(const q of data??[]){const bh=Array.isArray(q.bai_hoc)?q.bai_hoc[0]:q.bai_hoc;const cd=Array.isArray(bh?.chuyen_de)?bh.chuyen_de[0]:bh?.chuyen_de;const k=`${q.phan}|${cd?.chuyen_de_id}|${q.muc_do_id}`;if(!map.has(k))map.set(k,new Set);map.get(k)!.add(q.nhom_id??q.cau_hoi_id)}
 const sucChua=maTran.map(o=>({...o,khaDung:map.get(`${o.phan}|${o.chuyenDeId}|${o.mucDoId}`)?.size??0}));return {success:true,...kiemTraMaTran(maTran,sucChua,{I:m.phan1_so_cau??0,II:m.phan2_so_cau??0,III:m.phan3_so_cau??0})};
 }catch(e){return {success:false,error:e instanceof Error?e.message:"Có lỗi"}}
}
export async function taoDe(input:{caThiMonId:string;maTran:OMaTran[];soMaDe:number}){try{const check=await kiemTraSucChua(input.maTran);if(!check.success||!("hopLe" in check)||!check.hopLe)return {success:false,error:"Ma trận chưa hợp lệ"};const {u,s}=await ctx();const {data,error}=await s.rpc("tao_de_thi_nguyen_tu",{p_ca_thi_mon_id:input.caThiMonId,p_nguoi_tao_id:u.sub,p_ma_tran:input.maTran.map(o=>({phan:o.phan,chuyen_de_id:o.chuyenDeId,muc_do_id:o.mucDoId,so_luong:o.soLuong})),p_so_ma_de:input.soMaDe});if(error)throw new Error("Chưa tạo được đề thi. Vui lòng kiểm tra ma trận và thử lại.");revalidatePath("/de-thi");return {success:true,id:data as string}}catch(e){return {success:false,error:e instanceof Error?e.message:"Chưa tạo được đề thi. Vui lòng thử lại."}}}
export async function chuanBiPreview(maTran:OMaTran[],soMaDe:number){
 try{const {s,m}=await ctx();if(soMaDe<1||soMaDe>4)throw new Error("Số mã đề không hợp lệ");
 const {data,error}=await s.from("cau_hoi").select("cau_hoi_id,phan,muc_do_id,nhom_id,noi_dung,chi_tiet_cau_hoi(thu_tu,noi_dung),bai_hoc!inner(chuyen_de!inner(chuyen_de_id,mon_id))").eq("bai_hoc.chuyen_de.mon_id",m.mon_id).eq("trang_thai_duyet","DaDuyet").eq("trang_thai_su_dung","ChuaDung").eq("trang_thai_hoat_dong","DangHoatDong");if(error)throw new Error("Chưa tải được câu hỏi để tạo đề. Vui lòng thử lại.");
 const pool=(data??[]).map(q=>{const bh=Array.isArray(q.bai_hoc)?q.bai_hoc[0]:q.bai_hoc;const cd=Array.isArray(bh?.chuyen_de)?bh.chuyen_de[0]:bh?.chuyen_de;return{id:q.cau_hoi_id,phan:q.phan as CauHoiPreview["phan"],chuyenDeId:cd?.chuyen_de_id as string,mucDoId:q.muc_do_id,nhomId:q.nhom_id,noiDung:q.noi_dung,chiTiet:[...(q.chi_tiet_cau_hoi??[])].sort((a,b)=>a.thu_tu-b.thu_tu).map(x=>({thuTu:x.thu_tu,noiDung:x.noi_dung}))}}).sort(()=>Math.random()-.5);
 const used=new Set<string>();const maDe:CauHoiPreview[][]=[];
 for(let code=0;code<soMaDe;code++){const selected:CauHoiPreview[]=[];const groups=new Set<string>();for(const cell of maTran.filter(x=>x.soLuong>0)){const candidates=pool.filter(q=>!used.has(q.id)&&q.phan===cell.phan&&q.chuyenDeId===cell.chuyenDeId&&q.mucDoId===cell.mucDoId&&!groups.has(q.nhomId??q.id));if(candidates.length<cell.soLuong)throw new Error(`Không đủ câu cho Phần ${cell.phan} ở mã đề ${code+1}`);for(const q of candidates.slice(0,cell.soLuong)){selected.push(q);used.add(q.id);groups.add(q.nhomId??q.id)}}maDe.push(selected)}
 return{success:true,maDe};
 }catch(e){return{success:false,error:e instanceof Error?e.message:"Có lỗi"}}
}
export async function hoanDoiCau(cau:CauHoiPreview,daDung:string[],nhomTrongMa:string[]){try{const {s,m}=await ctx();const {data,error}=await s.from("cau_hoi").select("cau_hoi_id,phan,muc_do_id,nhom_id,noi_dung,chi_tiet_cau_hoi(thu_tu,noi_dung),bai_hoc!inner(chuyen_de!inner(chuyen_de_id,mon_id))").eq("bai_hoc.chuyen_de.mon_id",m.mon_id).eq("phan",cau.phan).eq("muc_do_id",cau.mucDoId).eq("bai_hoc.chuyen_de.chuyen_de_id",cau.chuyenDeId).eq("trang_thai_duyet","DaDuyet").eq("trang_thai_su_dung","ChuaDung").eq("trang_thai_hoat_dong","DangHoatDong").not("cau_hoi_id","in",`(${[...daDung,cau.id].join(",")})`).limit(100);if(error)throw new Error("Chưa tìm được câu thay thế. Vui lòng thử lại.");const q=(data??[]).filter(x=>!x.nhom_id||!nhomTrongMa.includes(x.nhom_id)).sort(()=>Math.random()-.5)[0];if(!q)throw new Error("Không còn câu thay thế phù hợp");return{success:true,cau:{...cau,id:q.cau_hoi_id,nhomId:q.nhom_id,noiDung:q.noi_dung,chiTiet:[...(q.chi_tiet_cau_hoi??[])].sort((a,b)=>a.thu_tu-b.thu_tu).map(x=>({thuTu:x.thu_tu,noiDung:x.noi_dung}))}}}catch(e){return{success:false,error:e instanceof Error?e.message:"Chưa đổi được câu hỏi. Vui lòng thử lại."}}}
export async function hoanTatDe(input:{dotThiId:string;maTran:OMaTran[];maDe:CauHoiPreview[][]}){try{const {u,s}=await ctx();const {data,error}=await s.rpc("tao_va_giao_de_theo_dot",{p_dot_thi_id:input.dotThiId,p_nguoi_tao_id:u.sub,p_ma_tran:input.maTran.map(o=>({phan:o.phan,chuyen_de_id:o.chuyenDeId,muc_do_id:o.mucDoId,so_luong:o.soLuong})),p_cau_hoi_theo_ma:input.maDe.map((qs,i)=>({so_ma:i+1,cau_hoi_ids:qs.map(q=>q.id)}))});if(error)throw new Error("Chưa hoàn tất được đề thi. Vui lòng kiểm tra lại và thử lại.");revalidatePath("/de-thi");return{success:true,id:data as string}}catch(e){return{success:false,error:e instanceof Error?e.message:"Chưa hoàn tất được đề thi. Vui lòng thử lại."}}}
export async function doiTrangThaiDe(id:string,action:"giao"|"huy"){try{const {u,s}=await ctx();const {error}=await s.rpc(action==="giao"?"giao_de_thi":"huy_de_dang_soan",{p_de_thi_id:id,p_nguoi_tao_id:u.sub});if(error)throw new Error("Chưa cập nhật được đề thi. Vui lòng tải lại trang và thử lại.");revalidatePath("/de-thi");return {success:true}}catch(e){return {success:false,error:e instanceof Error?e.message:"Chưa cập nhật được đề thi. Vui lòng thử lại."}}}
