import { taoSupabaseServiceRole } from "@/lib/supabase/server";
import EmailAction from "./EmailAction";
import { layTrangThaiGmail } from "@/lib/email/gmail-oauth";

export const dynamic = "force-dynamic";
const labels: Record<string, string> = { ChoGui: "Chờ gửi", DaGui: "Đã gửi", KhongGui_ThieuEmail: "Thiếu email", ThatBaiTamThoi: "Thất bại tạm thời", CanXuLyThuCong: "Cần xử lý thủ công" };

export default async function ThongBaoEmailPage({ searchParams }: { searchParams: Promise<{ trangThai?: string; gmail?: string }> }) {
  const { trangThai = "", gmail = "" } = await searchParams;
  const supabase = taoSupabaseServiceRole();
  const ketNoiGmail = await layTrangThaiGmail();
  const { data, error } = await supabase.from("bai_lam_thi").select("bai_lam_id,diem_tong,tai_khoan!bai_lam_thi_hoc_sinh_tai_khoan_id_fkey(ho_ten,ma_so,email_phu_huynh),ca_thi_mon!inner(mon(ten_mon),ca_thi!inner(dot_thi!inner(ten_dot_thi))),nhan_xet_ai(noi_dung),email_log(trang_thai,so_lan_thu,message_id,ma_loi,chi_tiet_loi,thoi_diem_gui,created_at)").eq("trang_thai", "DaNopBai").not("diem_tong", "is", null).order("thoi_diem_nop", { ascending: false }).limit(200);
  const rows = (data || []).filter((row) => { const log = Array.isArray(row.email_log) ? row.email_log[0] : row.email_log; const status = log?.trang_thai || "ChuaGui"; return !trangThai || status === trangThai; });
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Nhật ký email</h1><p className="text-sm text-muted-foreground">Theo dõi lịch sử gửi email kết quả cho phụ huynh và gửi lại khi cần. Nhận xét được quản lý tại mục Nhật ký báo cáo.</p></div>
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card p-4"><div><p className="font-semibold">Tài khoản gửi email</p><p className="text-sm text-muted-foreground">{ketNoiGmail ? `Đã kết nối: ${ketNoiGmail.email_gui}` : "Chưa kết nối tài khoản gửi"}</p>{gmail && <p className={gmail === "da-ket-noi" ? "text-sm text-emerald-700" : "text-sm text-destructive"}>{gmail === "da-ket-noi" ? "Đã kết nối Gmail." : "Chưa kết nối được Gmail. Vui lòng thử lại."}</p>}</div><a href="/api/auth/google/connect" className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">{ketNoiGmail ? "Đổi tài khoản gửi" : "Kết nối Gmail"}</a></div>
    <div className="flex flex-wrap gap-2">{[["", "Tất cả"], ["ChuaGui", "Chưa gửi"], ["DaGui", "Đã gửi"], ["ThatBaiTamThoi", "Gửi lỗi"], ["CanXuLyThuCong", "Cần xử lý"]].map(([value, label]) => <a key={value} href={value ? `?trangThai=${value}` : "/thong-bao-email"} className={`rounded-full border px-3 py-1 text-sm ${trangThai === value ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card hover:bg-muted"}`}>{label}</a>)}</div>
    {error ? <div className="rounded-xl bg-destructive/10 p-4 text-destructive">Chưa tải được danh sách email. Vui lòng tải lại trang.</div> : <div className="overflow-x-auto rounded-xl border border-border bg-card"><table className="w-full min-w-[950px] text-sm"><thead className="bg-muted/50"><tr><th className="p-3 text-left">Học sinh</th><th className="p-3 text-left">Bài thi</th><th className="p-3 text-left">Email phụ huynh</th><th className="p-3 text-left">Trạng thái gửi</th><th className="p-3 text-left">Thời điểm</th><th className="p-3 text-left">Thao tác</th></tr></thead><tbody>{rows.map((row) => { const tk = Array.isArray(row.tai_khoan) ? row.tai_khoan[0] : row.tai_khoan; const ctm = Array.isArray(row.ca_thi_mon) ? row.ca_thi_mon[0] : row.ca_thi_mon; const mon = Array.isArray(ctm?.mon) ? ctm.mon[0] : ctm?.mon; const ca = Array.isArray(ctm?.ca_thi) ? ctm.ca_thi[0] : ctm?.ca_thi; const dot = Array.isArray(ca?.dot_thi) ? ca.dot_thi[0] : ca?.dot_thi; const nx = Array.isArray(row.nhan_xet_ai) ? row.nhan_xet_ai[0] : row.nhan_xet_ai; const log = Array.isArray(row.email_log) ? row.email_log[0] : row.email_log; const status = log?.trang_thai || "ChuaGui"; return <tr key={row.bai_lam_id} className="border-t border-border align-top"><td className="p-3 font-semibold">{tk?.ho_ten}<div className="text-xs font-normal text-muted-foreground">{tk?.ma_so}</div></td><td className="p-3">{mon?.ten_mon}<div className="text-xs text-muted-foreground">{dot?.ten_dot_thi} · {Number(row.diem_tong).toFixed(2)} điểm</div></td><td className="p-3">{tk?.email_phu_huynh || <span className="text-amber-700">Thiếu email</span>}</td><td className="p-3"><span className="font-medium">{labels[status] || "Chưa gửi"}</span>{log?.ma_loi && <div className="text-xs text-destructive">{log.chi_tiet_loi || "Chưa gửi được. Vui lòng thử lại."}</div>}</td><td className="p-3 text-muted-foreground">{log?.thoi_diem_gui ? new Date(log.thoi_diem_gui).toLocaleString("vi-VN") : "—"}</td><td className="p-3"><EmailAction baiLamId={row.bai_lam_id} disabled={!tk?.email_phu_huynh || !nx?.noi_dung} sent={status === "DaGui"} /></td></tr>; })}</tbody></table></div>}
  </div>;
}
